server:
  port: 8100

application:
  name: todo-manager

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: 'root'
    url: 'jdbc:mariadb://localhost:3309/point'
    password: 'eddy'
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        storage_engine: innodb
    defer-datasource-initialization: true
